[package]
name = "punchball"
version = "0.1.0"
authors = ["Nathan Stocks <cleancut@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.0"
